<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ShowMeTheMoney</AssemblyName>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
    <Version>1.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <None Update="AppIcon.ico" CopyToOutputDirectory="PreserveNewest" />
    <None Update="donation.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
