'use client';
import {useState} from 'react';
export default function Home(){
 const [en,setEn]=useState(false);const t=(ko:string,enText:string)=>en?enText:ko;
 return <div className="page" lang={en?'en':'ko'}>
 <header><a className="brand" href="#"><img src="/app-icon.png" width="36" height="36" alt=""/>Show Me The Money</a><nav className="header-links" aria-label="Links"><a className="github-badge" href="https://github.com/slavelee777/showmethemoney" target="_blank" rel="noopener noreferrer">GitHub ↗</a><button className="language" onClick={()=>setEn(!en)} aria-label={t('Switch to English','한국어로 전환')}>{en?'한국어':'English'} ↗</button></nav></header>
 <main><div className="eyebrow"><span/> {t('무료 데스크톱 앱 · 1.0','FREE DESKTOP APP · 1.0')}</div>
 <h1>{t('주가만,','Your stock.')}<br/><em>{t('가볍게.','At a glance.')}</em></h1>
 <p className="intro">{t('차트를 열지 않아도 괜찮아요.','No need to keep a chart open.')}<br/>{t('일하는 화면 한쪽에서, 내 주식을 확인하세요.','Keep your stock in sight while you work.')}</p>
 <div className="downloads"><a className="primary" href="https://github.com/slavelee777/showmethemoney/releases/download/v1.0.1/ShowMeTheMoney-Mac.zip" download>↓ {t('Mac 다운로드','Download for Mac')}</a><a className="secondary" href="https://github.com/slavelee777/showmethemoney/releases/download/v1.0.1/ShowMeTheMoney-Windows.zip" download>↓ {t('Windows 다운로드','Download for Windows')}</a></div>
 <p className="download-count"><a href="https://github.com/slavelee777/showmethemoney/releases" target="_blank" rel="noopener noreferrer" title="전체 릴리스 다운로드 횟수 / Total release downloads"><img src="https://img.shields.io/github/downloads/slavelee777/showmethemoney/total?label=downloads&amp;color=c1f76c&amp;labelColor=192219" alt="GitHub release downloads" height="20" /></a></p>
 <p className="requirements">Mac · Apple Silicon / Intel · macOS 13+<br/>Windows x64 · .NET 10 Desktop Runtime <a href="https://dotnet.microsoft.com/en-us/download/dotnet/10.0" target="_blank" rel="noreferrer">{t('설치','Install')} ↗</a> · <a href="https://github.com/slavelee777/showmethemoney/releases/download/v1.0.1/ShowMeTheMoney-Windows-ARM64.zip" download>ARM64 ↓</a></p>
 <figure className="app-demo"><img src="/mac-demo.gif" width="620" height="724" loading="lazy" alt={t("Mac 주식 앱: 종목 검색과 가격 확인","Mac stock app: search and price display")}/><figcaption>{t("Mac UI · 사용 예시 · 예시 데이터","Mac UI · Demo · Sample data")}</figcaption></figure>
 <div className="sample" aria-label={t('앱 가격 표시 예시','Example price display')}><div className="sample-label">{t('이렇게, 한눈에','ONE QUICK LOOK')}<span>{t('표시 예시 · 실제 시세 아님','ILLUSTRATION · NOT LIVE')}</span></div><div className="mode-examples"><div><span>{t('현재가만','Current price')}</span><strong>$220.00</strong></div><div><span>{t('현재가 + 전일 대비','Price + daily change')}</span><strong>$220.00 <small>(+2.50%)</small></strong></div><div><span>{t('평가총액 + 보유 수익률','Holding value + return')}</span><strong>$2,200.00 <small>(+10.00%)</small></strong></div></div><p>{t('세 가지 모드 중 하나를 골라 표시하세요.','Choose one of three display modes.')}</p></div>
 <div className="features"><p><b>01</b>{t('검색하고 선택하면 끝','Search. Select. Done.')}</p><p><b>02</b>{t('평단과 수량으로 내 수익률','Your cost, shares & return')}</p><p><b>03</b>{t('한국어 · English','English · 한국어')}</p></div>
 <p className="note">{t('Mac은 메뉴 막대에, Windows는 작업표시줄 위 작은 가격창에 표시됩니다. 장중 국내 7초·해외 15초, 장 종료 시 60초마다 조회합니다. 시세가 지연될 수 있습니다.','Shown in the Mac menu bar or a small price window above the Windows taskbar. Quotes refresh every 7s (Korea) or 15s (overseas), and every 60s when closed. Data may be delayed.')}<br/>{t('한국어는 원화, 영어는 달러로 표시합니다. 전일 대비는 직전 거래일 종가 기준이며 환율 변동은 제외합니다.','Korean shows KRW; English shows USD. Daily change uses the previous trading day’s close and excludes FX changes.')}</p>
 </main><footer><span>{t('작게 만들고, 꾸준히 다듬습니다.','Small by design. Made with care.')}</span><a href="https://buymeacoffee.com/hglee" target="_blank" rel="noreferrer">♡ {t('개발자 커피 한 잔','Buy me a coffee')} ↗</a></footer></div>
}
